name: Build & Test
run-name: Build & Test
#
# Can run on pushes and manually triggerey
on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write # Required for the azure login action
  checks: write # Required for test-reporter action

jobs:
  echo-everything:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello, EVERYTHING"

