name: Build & Test
run-name: Build & Test
#
# Can run on pushes and manually triggered
on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write # Required for the azure login action
  checks: write # Required for test-reporter action

jobs:
  echo-everything:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "ECHO"
        run: |
          echo "Hello, EVERYTHING"

      - name: "TAG"
        uses: ag10717/spark-release-tag@v5

