name: Deploy to DEV
run-name: "DEV Deploy - Version: ${{ github.ref_name }}"

# Can run from other workflows or manually triggered
on:
  workflow_run:
    workflows:
      - "Build & Test"
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  id-token: write # Required for the azure login action
  checks: write # Required for test-reporter action

jobs:
  deploy:
    if: |
      (github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deployment
        env:
          REF_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
        run: |
          echo "REF_NAME: $REF_NAME"

          echo "Download Release"
          gh release download v1.0.1 --pattern "deployment.zip"
          echo "Download Complete"

          echo "Running Deployment"
          aws lambda update-function-code --function-name "helloworld-go" --zip-file "fileb://deployment.zip"
          echo "Completed Updating Function Code"
