name: Deploy to DEV

# Can run from other workflows or manually triggered
on:
  workflow_run:
    workflows: 
      - "Build & Test"
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  id-token: write # Required for the azure login action
  checks: write # Required for test-reporter action

jobs:
  echo-hello:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "ECHO"
        run: |
          echo "Hello, DEV"

      - name: "READ FILE"
        run: |
          while IFS= read -r line; do
            echo "LINE: $line"
          done < src/changing.md

